# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: Install Dependencies
        run: |
          gem install bundler
          cd project1/ers
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: |
          cd project1/ers
          bundle exec rubocop --auto-correct
        continue-on-error: true
          
      - name: Run Unit Tests
        run: |
          cd project1/ers
          rails db:migrate RAILS_ENV=test
          bundle exec rails test
        continue-on-error: true
          
  deployment:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          cd ../../../../
          git pull origin main
          cd /AD_Project1_Backend/project1/ers
          sudo bundle install --jobs 4 --retry 3
