# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: Install Dependencies
        run: |
          gem install bundler
          cd project1/ers
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: |
          cd project1/ers
          bundle exec rubocop --auto-correct
        continue-on-error: true
          
      - name: Run Unit Tests
        run: |
          cd project1/ers
          rails db:migrate RAILS_ENV=test
          bundle exec rails test
        continue-on-error: true
        
#   setuprunner:
# #     needs: test
#     runs-on: ubuntu-latest
#     steps:
      
#       - name: SSH into Ubuntu server
#         run: |
#           sudo apt-get install -y tmux
#           tmux new-session -d -s my-session 'bash'
#           tmux send-keys -t my-session 'ssh ${{ secrets.SSH_KEY }} ubuntu@ec2-3-134-85-143.us-east-2.compute.amazonaws.com' C-m
#           tmux send-keys -t my-session 'yes' C-m
#           tmux send-keys -t my-session 'cd actions-runner/' C-m
#           tmux send-keys -t my-session 'sudo ./svc.sh start' C-m
#           tmux send-keys -t my-session 'git pull origin main' C-m
#           tmux send-keys -t my-session 'cd ../' C-m 
#           tmux send-keys -t my-session 'sudo docker build ers -t ers2:Latest' C-m

  upload-artifact:
    runs-on: self-hosted
    steps:
      - name: CD into Project Files
        run: cd ../../../../AD_Project1_Backend/project1
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ERS Backend Artifact
          path: /ers
          
  deployment:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Build New Image
        run: |
          cd ../../../../AD_Project1_Backend/project1/ers
          git pull origin main
          cd ../
          sudo docker build ers -t ers:Latest
          
